config:
  create_root: true
  unrestricted: false
vars:
  project_name: 
    type: string
    required: true
  author_github_name: 
    type: string
    required: true
  license: 
    type: license
    required: false

# need support key:value ?

steps:
  - name: git init
    module: git
    action: init
  - name: go mod init
    module: go
    action: init
  - name: go get deps
    module: go
    action: install-local-deps
    cwd: frontend
    params:
      - github.com/charmbracelet/bubbletea
      - github.com/charmbracelet/log

folder_struct:
  - cmd:
    - install
    - remove
    - root.go
  - internal
  - main.go:
      template: 
        filepath: ./temp.go
        engine: jinja2
