version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: ["tar.gz", "zip"]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: ["zip"]
nfpms:
  - id: boot
    package_name: boot
    vendor: bootengine
    homepage: https://bootengine.github.io/
    maintainer: bootengine
    description: |
      boot is a higthly customizable project bootstrapper.  It comes with a plugin system that accepts .wasm files meaning that you can create plugins in anything that compile to wasm.
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux
    file_name_template: >-
      {{- trimsuffix .ConventionalFileName .ConventionalExtension -}}
      {{- if and (eq .Arm "6") (eq .ConventionalExtension ".deb") }}6{{ end -}}
      {{- if not (eq .Amd64 "v1")}}{{ .Amd64 }}{{ end -}}
      {{- .ConventionalExtension -}}
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

## Need to create man page and completion files before
#homebrew_casks:
#- name: boot
#  homepage: https://github.com/bootengine/
#  description: boot is a simple cli made to bootstrap any project with a plugin engine that allows you to enhance it using any programming language that can compile to wasm/wasi.
#  manpages:
#    - man/
#  completions:
#  zap:
#    delete:
#      - ~/.config/bootengine/
#  uninstall:
#    delete:
#      - ~/.config/bootengine/
#  repository:
#    owner: bootengine
#    name: homebrew-toools
#    branch: main

release:

  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
