name: Build Workflow
run-name: Check that the application is building
on: 
  push:
    tags:
      - "*"
permissions:
  packages: read
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Create plugin folder
        run: mkdir -p internal/assets/plugins
      - uses: robinraju/release-downloader@v1
        with:
            repository: 'bootengine/boot-git-plugin'
            #latest: true
            fileName: 'boot-git-plugin.wasm'
            out-file-path: 'internal/assets/plugins/boot-git.wasm'
            # ------- 
            # need to get the tag dynamically
            # ------- 
            tag: 'v0.9.3-beta'
            secret: ${{secrets.GITHUB_TOKEN}}
      - uses: robinraju/release-downloader@v1
        with:
            repository: 'bootengine/boot-filer-plugin'
            #latest: true
            fileName: 'boot-filer-plugin.wasm'
            out-file-path: 'internal/assets/plugins/boot-filer.wasm'
            # ------- 
            # need to get the tag dynamically
            # ------- 
            tag: 'v0.9.5-beta'
            secret: ${{secrets.GITHUB_TOKEN}}
      - uses: robinraju/release-downloader@v1
        with:
            repository: 'bootengine/boot-template-plugin'
            #latest: true
            fileName: 'boot-template-plugin.wasm'
            out-file-path: 'internal/assets/plugins/boot-template.wasm'
            # ------- 
            # need to get the tag dynamically
            # ------- 
            tag: 'v0.9.0-beta'
            secret: ${{secrets.GITHUB_TOKEN}}
      - name: check
        run: ls -la internal/assets/plugins
